version: "3"

services:
  app:
    build: ./laravel
    container_name: app
    entrypoint: php-fpm
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
